spring:
  application:
    name: flight-search
  config:
    import: optional:file:.env[.properties]
flight:
  providers:
    duffel:
      base-url: https://api.duffel.com
      token: ${DUFFEL_ACCESS_TOKEN:}
      timeout: 5000
      max-response-size: 10485760
    flightapi:
      base-url: https://api.flightapi.io
      api-key: ${FLIGHTAPI_KEY:}
      timeout: 20000
      max-response-size: 10485760
    aviationstack:
      base-url: https://api.aviationstack.com/v1
      api-key: ${AVIATIONSTACK_KEY:}
      timeout: 20000
      max-response-size: 10485760

#    amadeus:
#      base-url: https://test.api.amadeus.com  # Example for Amadeus sandbox
#      client-id: ${AMADEUS_CLIENT_ID}
#      client-secret: ${AMADEUS_CLIENT_SECRET}
#      timeout: 5000
logging:
  level:
    root: INFO
    com.apiintegration.flightsearch: DEBUG